#Each new term in the Fibonacci sequence is generated by 
#adding the previous two terms. By starting with 1 and 2, 
#the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#Find the sum of all the even-valued terms in the sequence 
#which do not exceed four million.

$x = 1;
$y = 2;

$sum = 2;

for(3 .. 1000)
{
	if($y > 4000000) {
		last;
	}
	else {
		($x,$y) = ($y, $x+$y);
		print "$y ";
		if($y % 2 == 0) {
			$sum+=$y;
		}
	}	
}

print "\nSum: $sum";
